apiVersion: v1
kind: Pod
metadata:
  name: atharva-pod
spec:
  containers:
  - name: atharva-container1
    image: nginx
    ports:
    - containerPort: 80
    
  - name: atharva-container2
    image: ubuntu
    ports:
    - containerPort: 80