replicaCount: 2

container:
  name: atharva-container1
  image: atharva7823/fitnesstracker:v1
  containerPort: 5000

service:
  name: atharva-service1
  port: 5000
  targetPort: 5000
  type: LoadBalancer

configMap:
  name: atharva-configmap1
  data:
    APP_NAME: "Fitness-App"
    APP_PORT: "5000"

secret:
  name: atharva-secret1
  type: Opaque
  data:
    DB_USER: YWRtaW4=
    DB_PASSWORD: YXRoYXJ2YUA3ODIz